import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.about': 'About',
    'nav.rooms': 'Rooms',
    'nav.spaces': 'Spaces',
    'nav.location': 'Location',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.eyebrow': 'Opening October · Lisbon',
    'hero.softlaunch': 'Soft Launch July',
    'hero.headline.pre': 'A new boutique coliving opening in',
    'hero.headline.accent': 'Lisbon',
    'hero.headline.post': 'this October',
    'hero.subheadline': 'A thoughtfully designed home for people in mobility — combining privacy, community, and design in a central Lisbon location.',
    'hero.cta': "I'm interested",
    'hero.learnMore': 'Learn more',
    
    // Mid-page CTA
    'midcta.text': 'Interested in joining us? We\'re now collecting expressions of interest for October.',
    'midcta.cta': 'Reserve your spot',
    
    // What is
    'whatis.label': 'The Concept',
    'whatis.title.pre': 'What is Living',
    'whatis.title.accent': 'Colours',
    'whatis.title.post': 'AR?',
    'whatis.intro': 'Living Colours celebrates the light and colours of Lisboa. Preserving its architecture, its uniqueness and its sophisticated simplicity - we are creating a place where you enjoy your privacy with a cozy set of amenities on a bespoke community environment.',
    'whatis.pillar1.title': 'A Real Home',
    'whatis.pillar2.title': 'Quality Without Compromise',
    'whatis.pillar3.title': 'Community by Design',
    'whatis.p1': 'We are creating a boutique coliving residence — a thoughtfully designed home for people in transition. Not a hotel, not a hostel, not a student dormitory. A place to truly live.',
    'whatis.p2': 'We believe temporary living should not mean temporary quality. Every detail — from the furniture to the community — is considered to create a sense of belonging, even if your stay is measured in months.',
    'whatis.p3': 'Private spaces with shared values. Considered design at accessible prices. A community that feels like home.',
    
    // Who it's for
    'who.label': 'Our Residents',
    'who.title': 'Who is it for?',
    'who.intro': 'Living Colours AR welcomes those who share our values: curiosity, respect, and the desire to live well, wherever life takes them.',
    'who.student.title': 'Students in Mobility',
    'who.student.desc': 'Pursuing studies abroad with a need for stability and focus.',
    'who.professional.title': 'Young Professionals',
    'who.professional.desc': 'Starting a new chapter in Lisbon, seeking quality without long-term commitment.',
    'who.nomad.title': 'Digital Nomads',
    'who.nomad.desc': 'Working remotely while exploring what Lisbon has to offer.',
    'who.relocating.title': 'People Relocating',
    'who.relocating.desc': 'Settling into the city while searching for their permanent home.',
    
    // What's included
    'included.label': 'Living Here',
    'included.title': 'What\'s included',
    'included.intro': 'Everything you need for a comfortable, productive, and connected life.',
    'included.rooms': 'Fully Furnished Rooms',
    'included.rooms.desc': 'Thoughtfully designed private spaces with quality furniture, linens, and storage.',
    'included.kitchen': 'Shared Kitchens',
    'included.kitchen.desc': 'Well-equipped kitchens on every floor for daily cooking and shared meals.',
    'included.cleaning': 'Regular Cleaning',
    'included.cleaning.desc': 'Weekly cleaning of your room and daily maintenance of common areas.',
    'included.cowork': 'Cowork & Lounge',
    'included.cowork.desc': 'Dedicated spaces to work, meet, and relax with reliable high-speed internet.',
    'included.events': 'Community Events',
    'included.events.desc': 'Regular gatherings, dinners, and activities to connect with fellow residents.',
    'included.management': 'On-site Management',
    'included.management.desc': 'A dedicated team to support you and maintain the quality of life here.',
    
    // Rooms
    'rooms.label': 'Room Types',
    'rooms.title': 'Find your space',
    'rooms.intro': 'Five room categories designed to suit different needs and preferences. All rooms are private, fully furnished, and include utilities.',
    'rooms.smart': 'Smart',
    'rooms.smart.desc': 'An efficient entry point — essential, well thought out, and easy on the budget. Designed for people who spend most of the day out exploring Lisbon.',
    'rooms.standard': 'Standard',
    'rooms.standard.desc': 'A balanced, comfortable option — the natural step up from Smart, with a bit more room to settle in and a sense of home for longer stays.',
    'rooms.premium': 'Premium',
    'rooms.premium.desc': 'Where the room becomes a place to spend real time — more space and comfort for people who work or study from home.',
    'rooms.suite': 'Suite',
    'rooms.suite.desc': 'Less space, more freedom. A private bathroom of your own — your own corner, no sharing, full autonomy in your daily routine.',
    'rooms.master': 'Master Suite',
    'rooms.master.desc': 'The top of the range — space and privacy together. The closest you can get to a small apartment within the coliving.',
    'rooms.from': 'From',
    'rooms.month': '/month',
    'rooms.priceOnRequest': 'Price on request',
    'rooms.learnMore': 'Learn more',
    'rooms.privateBathroom': 'Private bathroom',
    'rooms.sharedBathroom': 'Shared bathroom',
    'rooms.size.smart': '~9 m²',
    'rooms.size.standard': '11–13 m²',
    'rooms.size.premium': '15–20 m²',
    'rooms.size.suite': '~12 m²',
    'rooms.size.master': '18–25 m²',
    'rooms.area': 'Area',
    'rooms.close': 'Close',
    'rooms.smart.detail': 'The Smart room is an efficient, well-considered entry point — not low-tier, just essential. Around 9 m² with everything you need: a comfortable bed, a functional workspace, storage, and natural light. Shared bathroom on the floor. Ideal for price-sensitive guests who spend most of the day out in the city.',
    'rooms.standard.detail': 'The Standard room is the balanced choice — 11 to 13 m² of comfortable, well-designed space. A natural step up from Smart, with more room to settle in for medium and longer stays. Comfortable bed, dedicated desk, storage, and good natural light. Shared bathroom on the floor.',
    'rooms.premium.detail': 'The Premium room is where you gain real space and comfort to spend time inside — 15 to 20 m², made for people who work or study from home. Generous workspace, comfortable bed, ample storage, and great natural light. Shared bathroom on the floor.',
    'rooms.suite.detail': 'The Suite is about autonomy and privacy — its defining feature is a private bathroom of your own, not the size of the room. Around 12 m², thoughtfully arranged, with a comfortable bed, workspace, and storage. Less space, more freedom: your own corner, no sharing, full control of your daily routine.',
    'rooms.master.detail': 'The Master Suite is the top of the range — 18 to 25 m² that combine space and privacy. Comfortable bed, dedicated living and work areas, generous storage, and a private bathroom. Some Master Suites include a balcony. The closest experience to a small apartment within the coliving.',
    
    // Common spaces
    'spaces.label': 'Common Areas',
    'spaces.title': 'Spaces to share',
    'spaces.intro': 'Beyond your private room, Living Colours AR offers thoughtfully designed spaces for work, relaxation, and connection.',
    'spaces.cowork.title': 'Cowork & Lounge',
    'spaces.cowork.desc': 'A quiet, professional environment with ergonomic seating, high-speed wifi, and natural light. Perfect for focused work or video calls.',
    'spaces.cowork.detail': 'The cowork area features standing desks, private phone booths, a communal table for collaborative work, and a lounge area for more relaxed working. Printing and scanning facilities are available, along with lockers for your equipment.',
    'spaces.meeting.title': 'Meeting Rooms',
    'spaces.meeting.desc': 'Reservable private rooms for calls, interviews, or small gatherings. Equipped and ready when you need them.',
    'spaces.meeting.detail': 'Two fully equipped meeting rooms with video conferencing capabilities, whiteboards, and comfortable seating for up to 6 people. Book through our resident app for free.',
    'spaces.kitchen.title': 'Community Kitchen',
    'spaces.kitchen.desc': 'A larger kitchen space designed for community dinners, cooking classes, and shared moments.',
    'spaces.kitchen.detail': 'Our community kitchen is equipped with professional-grade appliances, a large island for group cooking, and dining space for up to 20 people. Regular community dinners and cooking events are organized here.',
    'spaces.coming': 'Coming Soon',
    'spaces.cinema.title': 'Cinema Room',
    'spaces.cinema.desc': 'A cozy screening room for movie nights and shared entertainment.',
    'spaces.cinema.detail': 'A dedicated screening room with a 120" projector, surround sound system, comfortable recliners, and ambient lighting. Available for residents to book for private screenings or community movie nights.',
    'spaces.gym.title': 'Fitness Area',
    'spaces.gym.desc': 'A compact gym space for residents who want to stay active without leaving home.',
    'spaces.gym.detail': 'Our fitness area includes cardio equipment, free weights, yoga mats, and a stretching zone. Open 24/7 for residents. Yoga and fitness classes will be organized regularly.',
    
    // Location
    'location.label': 'The Neighborhood',
    'location.title': 'Almirante Reis, Lisbon',
    'location.intro': 'One of Lisbon\'s most vibrant and authentic avenues. A neighborhood that balances tradition with creativity.',
    'location.central': 'Central Location',
    'location.central.desc': 'In the heart of Lisbon, with the city\'s best neighborhoods just minutes away.',
    'location.metro': 'Metro at Your Door',
    'location.metro.desc': 'Direct access to the green line, connecting you to the entire city.',
    'location.authentic': 'Authentic Lisbon',
    'location.authentic.desc': 'Local shops, markets, cafes, and restaurants that define the real Lisbon experience.',
    'location.diverse': 'Diverse & Creative',
    'location.diverse.desc': 'A multicultural neighborhood known for its arts scene and welcoming atmosphere.',
    
    // Pre-launch
    'prelaunch.label': 'Opening October 2026',
    'prelaunch.title': 'Now collecting expressions of interest',
    'prelaunch.p1': 'We are opening in October and currently welcoming expressions of interest from future residents.',
    'prelaunch.p2': 'Leave your details and we\'ll be in touch to discuss your plans and preferred room type.',
    'prelaunch.cta': "I'm interested",
    'prelaunch.days': 'Days',
    'prelaunch.hours': 'Hours',
    'prelaunch.minutes': 'Min',
    'prelaunch.seconds': 'Sec',

    // Soft Launch
    'softlaunch.title': 'Soft Launch — July 2026',
    'softlaunch.desc': 'Can\'t wait until October? We\'re opening a limited number of rooms in July with a significant early-bird discount until the full opening. Some amenities will still be in progress, but you\'ll be the first to experience Living Colours AR.',
    'softlaunch.bullet1': 'Limited rooms available from July',
    'softlaunch.bullet2': 'Significant discount on rent until full October opening',
    'softlaunch.bullet3': 'Some common areas and amenities will open progressively',
    'softlaunch.cta': 'Join the soft launch',
    
    // Contact form
    'form.title': 'Express your interest',
    'form.subtitle': 'Tell us about yourself and we\'ll be in touch to discuss your plans.',
    'form.name': 'Full name',
    'form.nationality': 'Nationality',
    'form.email': 'Email',
    'form.phone': 'WhatsApp / Phone number',
    'form.arrivalWindow': 'When would you like to move in?',
    'form.arrivalWindow.july2026': 'July 2026 (Soft Launch)',
    'form.arrivalWindow.august2026': 'August 2026',
    'form.arrivalWindow.september2026': 'September 2026',
    'form.arrivalWindow.october2026': 'October 2026 (Opening)',
    'form.arrivalWindow.november2026': 'November 2026',
    'form.arrivalWindow.december2026': 'December 2026',
    'form.arrivalWindow.january2027': 'January 2027',
    'form.arrivalWindow.february2027': 'February 2027',
    'form.arrivalWindow.march2027': 'March 2027',
    'form.arrivalWindow.april2027': 'April 2027',
    'form.arrivalWindow.may2027': 'May 2027',
    'form.arrivalWindow.june2027': 'June 2027',
    'form.arrivalWindow.july2027': 'July 2027',
    'form.arrivalWindow.august2027': 'August 2027',
    'form.arrivalWindow.september2027': 'September 2027',
    'form.arrivalWindow.october2027': 'October 2027',
    'form.arrivalWindow.november2027': 'November 2027',
    'form.arrivalWindow.december2027': 'December 2027',
    'form.arrivalWindow.later': '2028 or later / Not sure yet',
    'form.referral': 'How did you hear about us?',
    'form.referral.instagram': 'Instagram',
    'form.referral.recommendation': 'Recommendation from a friend',
    'form.referral.google': 'Google / Search',
    'form.referral.other': 'Other',
    'form.stay': 'Preferred length of stay',
    'form.stay.3-6': '3-6 months',
    'form.stay.6-12': '6-12 months',
    'form.stay.12+': '12+ months',
    'form.room': 'Preferred room type (optional)',
    'form.room.any': 'No preference',
    'form.about': 'What brings you to Lisbon?',
    'form.about.placeholder': 'Tell us a little about your plans (optional)',
    'form.submit': 'Send my interest',
    'form.success': 'Thank you for your interest! We\'ll be in touch soon.',
    'form.consent': 'I agree to be contacted by Living Colours about my application, in line with the Privacy Policy.',
    'form.error': 'Something went wrong. Please try again.',
    
    // FAQ
    'faq.label': 'Questions',
    'faq.title': 'Frequently asked questions',
    'faq.q1': 'Is this a student residence?',
    'faq.a1': 'Living Colours AR is a coliving space, not a traditional student residence. While we welcome students, we also welcome young professionals, digital nomads, and anyone in mobility who values quality living.',
    'faq.q2': 'Are short stays allowed?',
    'faq.a2': 'Our minimum stay is 3 months. We\'re designed for residents seeking stability, not short-term visitors.',
    'faq.q3': 'What is the minimum stay?',
    'faq.a3': 'The minimum stay is 3 months. Most of our residents stay between 6-12 months.',
    'faq.q4': 'Are prices all-inclusive?',
    'faq.a4': 'Yes. Your monthly rent includes utilities, high-speed internet, regular cleaning, and access to all common areas and amenities.',
    'faq.q5': 'Can I visit before booking?',
    'faq.a5': 'Absolutely. Once the building is ready, we\'ll be happy to arrange a visit. Express your interest and we\'ll keep you informed.',
    'faq.q6': 'How does the community work?',
    'faq.a6': 'We organize regular events and provide spaces for connection, but community is never forced. You choose how social you want to be.',
    'faq.q7': 'What is the soft launch in July?',
    'faq.a7': 'Before our full October opening, we\'re making a limited number of rooms available from July at a discounted rate. Some amenities will still be in progress, but you\'ll enjoy a reduced price until the full opening. It\'s a great opportunity for early residents.',
    
    // Footer
    'footer.tagline': 'Boutique coliving in Lisbon',
    'footer.contact': 'Contact',
    'footer.address': 'Avenida Almirante Reis, Lisbon',
    'footer.rights': 'All rights reserved.',
  },
  pt: {
    // Navigation
    'nav.about': 'Sobre',
    'nav.rooms': 'Quartos',
    'nav.spaces': 'Espaços',
    'nav.location': 'Localização',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contacto',
    
    // Hero
    'hero.eyebrow': 'Abertura em Outubro · Lisboa',
    'hero.softlaunch': 'Soft Launch Julho',
    'hero.headline.pre': 'Um novo coliving boutique abre em',
    'hero.headline.accent': 'Lisboa',
    'hero.headline.post': 'em Outubro',
    'hero.subheadline': 'Uma casa cuidadosamente desenhada para pessoas em mobilidade — combinando privacidade, comunidade e design numa localização central de Lisboa.',
    'hero.cta': 'Tenho interesse',
    'hero.learnMore': 'Saber mais',
    
    // Mid-page CTA
    'midcta.text': 'Tem interesse em juntar-se a nós? Estamos a recolher manifestações de interesse para Outubro.',
    'midcta.cta': 'Reserve o seu lugar',
    
    // What is
    'whatis.label': 'O Conceito',
    'whatis.title.pre': 'O que é a Living',
    'whatis.title.accent': 'Colours',
    'whatis.title.post': 'AR?',
    'whatis.intro': 'A Living Colours celebra a luz e as cores de Lisboa. Preservando a sua arquitetura, a sua singularidade e a sua simplicidade sofisticada — estamos a criar um lugar onde pode desfrutar da sua privacidade, com um conjunto acolhedor de comodidades, num ambiente de comunidade único.',
    'whatis.pillar1.title': 'Uma Verdadeira Casa',
    'whatis.pillar2.title': 'Qualidade Sem Compromisso',
    'whatis.pillar3.title': 'Comunidade por Design',
    'whatis.p1': 'Estamos a criar uma residência de coliving boutique — uma casa cuidadosamente desenhada para pessoas em transição. Não é um hotel, não é um hostel, não é uma residência de estudantes. Um lugar para realmente viver.',
    'whatis.p2': 'Acreditamos que viver temporariamente não deve significar qualidade temporária. Cada detalhe — do mobiliário à comunidade — é pensado para criar um sentido de pertença, mesmo que a sua estadia seja medida em meses.',
    'whatis.p3': 'Espaços privados com valores partilhados. Design cuidado a preços acessíveis. Uma comunidade que se sente como casa.',
    
    // Who it's for
    'who.label': 'Os Nossos Residentes',
    'who.title': 'Para quem é?',
    'who.intro': 'O Living Colours AR dá as boas-vindas a quem partilha os nossos valores: curiosidade, respeito, e o desejo de viver bem, onde quer que a vida os leve.',
    'who.student.title': 'Estudantes em Mobilidade',
    'who.student.desc': 'A estudar no estrangeiro com necessidade de estabilidade e foco.',
    'who.professional.title': 'Jovens Profissionais',
    'who.professional.desc': 'A começar um novo capítulo em Lisboa, procurando qualidade sem compromisso a longo prazo.',
    'who.nomad.title': 'Nómadas Digitais',
    'who.nomad.desc': 'A trabalhar remotamente enquanto exploram o que Lisboa tem para oferecer.',
    'who.relocating.title': 'Pessoas em Transição',
    'who.relocating.desc': 'A instalar-se na cidade enquanto procuram a sua casa permanente.',
    
    // What's included
    'included.label': 'Viver Aqui',
    'included.title': 'O que está incluído',
    'included.intro': 'Tudo o que precisa para uma vida confortável, produtiva e conectada.',
    'included.rooms': 'Quartos Mobilados',
    'included.rooms.desc': 'Espaços privados cuidadosamente desenhados com mobiliário de qualidade, roupa de cama e arrumação.',
    'included.kitchen': 'Cozinhas Partilhadas',
    'included.kitchen.desc': 'Cozinhas bem equipadas em cada piso para cozinhar diariamente e refeições partilhadas.',
    'included.cleaning': 'Limpeza Regular',
    'included.cleaning.desc': 'Limpeza semanal do seu quarto e manutenção diária das áreas comuns.',
    'included.cowork': 'Cowork & Lounge',
    'included.cowork.desc': 'Espaços dedicados para trabalhar, reunir e relaxar com internet de alta velocidade.',
    'included.events': 'Eventos Comunitários',
    'included.events.desc': 'Encontros regulares, jantares e atividades para conectar com outros residentes.',
    'included.management': 'Gestão no Local',
    'included.management.desc': 'Uma equipa dedicada para o apoiar e manter a qualidade de vida aqui.',
    
    // Rooms
    'rooms.label': 'Tipologias',
    'rooms.title': 'Encontre o seu espaço',
    'rooms.intro': 'Cinco categorias de quartos desenhadas para diferentes necessidades e preferências. Todos os quartos são privados, mobilados e incluem despesas.',
    'rooms.smart': 'Smart',
    'rooms.smart.desc': 'Uma porta de entrada eficiente — essencial, bem pensada e amiga do orçamento. Desenhada para quem passa a maior parte do dia a explorar Lisboa.',
    'rooms.standard': 'Standard',
    'rooms.standard.desc': 'Uma opção equilibrada e confortável — o passo natural a seguir ao Smart, com mais margem para se instalar e sensação de casa em estadias mais longas.',
    'rooms.premium': 'Premium',
    'rooms.premium.desc': 'O patamar em que o quarto passa a ser um sítio para estar de verdade — mais espaço e conforto para quem trabalha ou estuda a partir de casa.',
    'rooms.suite': 'Suite',
    'rooms.suite.desc': 'Menos espaço, mais liberdade. Uma casa de banho só sua — o seu próprio cantinho, sem partilhas, com autonomia total no dia a dia.',
    'rooms.master': 'Master Suite',
    'rooms.master.desc': 'O topo de gama — espaço e privacidade ao mesmo tempo. A experiência mais próxima de um pequeno apartamento dentro do coliving.',
    'rooms.from': 'Desde',
    'rooms.month': '/mês',
    'rooms.priceOnRequest': 'Preço sob consulta',
    'rooms.learnMore': 'Saber mais',
    'rooms.privateBathroom': 'Casa de banho privativa',
    'rooms.sharedBathroom': 'Casa de banho partilhada',
    'rooms.size.smart': '~9 m²',
    'rooms.size.standard': '11–13 m²',
    'rooms.size.premium': '15–20 m²',
    'rooms.size.suite': '~12 m²',
    'rooms.size.master': '18–25 m²',
    'rooms.area': 'Área',
    'rooms.close': 'Fechar',
    'rooms.smart.detail': 'O quarto Smart é uma porta de entrada eficiente e bem pensada — não é "low tier", é essencial. Cerca de 9 m² com o que precisa: cama confortável, espaço de trabalho funcional, arrumação e luz natural. Casa de banho partilhada no piso. Ideal para quem é sensível ao preço e passa a maior parte do dia na cidade.',
    'rooms.standard.detail': 'O quarto Standard é a escolha equilibrada — 11 a 13 m² de espaço confortável e bem desenhado. O passo natural a seguir ao Smart, com mais margem para se instalar em estadias médias e longas. Cama confortável, secretária dedicada, arrumação e boa luz natural. Casa de banho partilhada no piso.',
    'rooms.premium.detail': 'O quarto Premium é onde ganha espaço e conforto reais para estar dentro de casa — 15 a 20 m², pensado para quem trabalha ou estuda a partir do quarto. Área de trabalho generosa, cama confortável, ampla arrumação e muita luz natural. Casa de banho partilhada no piso.',
    'rooms.suite.detail': 'A Suite é sobre autonomia e privacidade — o seu traço central é a casa de banho privativa, não o tamanho do quarto. Cerca de 12 m², cuidadosamente organizados, com cama confortável, espaço de trabalho e arrumação. Menos espaço, mais liberdade: o seu próprio cantinho, sem partilhas, com total controlo do seu dia a dia.',
    'rooms.master.detail': 'A Master Suite é o topo de gama — 18 a 25 m² que combinam espaço e privacidade. Cama confortável, zonas dedicadas de estar e trabalho, arrumação generosa e casa de banho privativa. Algumas Master Suites incluem varanda. A experiência mais próxima de um pequeno apartamento dentro do coliving.',
    
    // Common spaces
    'spaces.label': 'Áreas Comuns',
    'spaces.title': 'Espaços para partilhar',
    'spaces.intro': 'Para além do seu quarto privado, o Living Colours AR oferece espaços cuidadosamente desenhados para trabalho, relaxamento e conexão.',
    'spaces.cowork.title': 'Cowork & Lounge',
    'spaces.cowork.desc': 'Um ambiente calmo e profissional com assentos ergonómicos, wifi de alta velocidade e luz natural. Perfeito para trabalho focado ou videochamadas.',
    'spaces.cowork.detail': 'A área de cowork inclui secretárias de pé, cabines telefónicas privadas, uma mesa comunitária para trabalho colaborativo e uma zona lounge. Serviços de impressão e digitalização disponíveis, com cacifos para equipamento.',
    'spaces.meeting.title': 'Salas de Reunião',
    'spaces.meeting.desc': 'Salas privadas reserváveis para chamadas, entrevistas ou pequenas reuniões. Equipadas e prontas quando precisar.',
    'spaces.meeting.detail': 'Duas salas de reunião totalmente equipadas com capacidade para videoconferência, quadros brancos e assentos confortáveis para até 6 pessoas. Reserve gratuitamente através da nossa app de residentes.',
    'spaces.kitchen.title': 'Cozinha Comunitária',
    'spaces.kitchen.desc': 'Um espaço de cozinha maior para jantares comunitários, aulas de culinária e momentos partilhados.',
    'spaces.kitchen.detail': 'A nossa cozinha comunitária está equipada com eletrodomésticos profissionais, uma ilha grande para cozinhar em grupo e espaço de jantar para até 20 pessoas. Jantares e eventos culinários são organizados regularmente.',
    'spaces.coming': 'Em Breve',
    'spaces.cinema.title': 'Sala de Cinema',
    'spaces.cinema.desc': 'Uma sala acolhedora para noites de cinema e entretenimento partilhado.',
    'spaces.cinema.detail': 'Uma sala de projeção dedicada com projetor de 120", sistema de som surround, reclinatórios confortáveis e iluminação ambiente. Disponível para reserva pelos residentes.',
    'spaces.gym.title': 'Área Fitness',
    'spaces.gym.desc': 'Um espaço de ginásio compacto para residentes que querem manter-se ativos sem sair de casa.',
    'spaces.gym.detail': 'A nossa área fitness inclui equipamento de cardio, pesos livres, tapetes de yoga e zona de alongamentos. Aberta 24/7 para residentes. Aulas de yoga e fitness serão organizadas regularmente.',
    
    // Location
    'location.label': 'O Bairro',
    'location.title': 'Almirante Reis, Lisboa',
    'location.intro': 'Uma das avenidas mais vibrantes e autênticas de Lisboa. Um bairro que equilibra tradição com criatividade.',
    'location.central': 'Localização Central',
    'location.central.desc': 'No coração de Lisboa, com os melhores bairros da cidade a poucos minutos.',
    'location.metro': 'Metro à Porta',
    'location.metro.desc': 'Acesso direto à linha verde, conectando-o a toda a cidade.',
    'location.authentic': 'Lisboa Autêntica',
    'location.authentic.desc': 'Lojas locais, mercados, cafés e restaurantes que definem a verdadeira experiência lisboeta.',
    'location.diverse': 'Diverso & Criativo',
    'location.diverse.desc': 'Um bairro multicultural conhecido pela sua cena artística e atmosfera acolhedora.',
    
    // Pre-launch
    'prelaunch.label': 'Abertura Outubro 2026',
    'prelaunch.title': 'A recolher manifestações de interesse',
    'prelaunch.p1': 'Abrimos em Outubro e estamos a receber manifestações de interesse de futuros residentes.',
    'prelaunch.p2': 'Deixe os seus dados e entraremos em contacto para discutir os seus planos e tipo de quarto preferido.',
    'prelaunch.cta': 'Tenho interesse',
    'prelaunch.days': 'Dias',
    'prelaunch.hours': 'Horas',
    'prelaunch.minutes': 'Min',
    'prelaunch.seconds': 'Seg',

    // Soft Launch
    'softlaunch.title': 'Soft Launch — Julho 2026',
    'softlaunch.desc': 'Não consegue esperar até Outubro? Vamos abrir um número limitado de quartos em Julho com um desconto significativo de early-bird até à abertura completa. Algumas comodidades ainda estarão em desenvolvimento, mas será dos primeiros a viver no Living Colours AR.',
    'softlaunch.bullet1': 'Quartos limitados disponíveis a partir de Julho',
    'softlaunch.bullet2': 'Desconto significativo na renda até à abertura completa em Outubro',
    'softlaunch.bullet3': 'Algumas áreas comuns e comodidades abrirão progressivamente',
    'softlaunch.cta': 'Quero o soft launch',
    
    // Contact form
    'form.title': 'Manifeste o seu interesse',
    'form.subtitle': 'Conte-nos sobre si e entraremos em contacto para discutir os seus planos.',
    'form.name': 'Nome completo',
    'form.nationality': 'Nacionalidade',
    'form.email': 'Email',
    'form.phone': 'WhatsApp / Número de telefone',
    'form.arrivalWindow': 'Quando gostarias de te mudar?',
    'form.arrivalWindow.july2026': 'Julho 2026 (Soft Launch)',
    'form.arrivalWindow.august2026': 'Agosto 2026',
    'form.arrivalWindow.september2026': 'Setembro 2026',
    'form.arrivalWindow.october2026': 'Outubro 2026 (Abertura)',
    'form.arrivalWindow.november2026': 'Novembro 2026',
    'form.arrivalWindow.december2026': 'Dezembro 2026',
    'form.arrivalWindow.january2027': 'Janeiro 2027',
    'form.arrivalWindow.february2027': 'Fevereiro 2027',
    'form.arrivalWindow.march2027': 'Março 2027',
    'form.arrivalWindow.april2027': 'Abril 2027',
    'form.arrivalWindow.may2027': 'Maio 2027',
    'form.arrivalWindow.june2027': 'Junho 2027',
    'form.arrivalWindow.july2027': 'Julho 2027',
    'form.arrivalWindow.august2027': 'Agosto 2027',
    'form.arrivalWindow.september2027': 'Setembro 2027',
    'form.arrivalWindow.october2027': 'Outubro 2027',
    'form.arrivalWindow.november2027': 'Novembro 2027',
    'form.arrivalWindow.december2027': 'Dezembro 2027',
    'form.arrivalWindow.later': '2028 ou mais tarde / Ainda não sei',
    'form.referral': 'Como soubeste de nós?',
    'form.referral.instagram': 'Instagram',
    'form.referral.recommendation': 'Recomendação de um amigo',
    'form.referral.google': 'Google / Pesquisa',
    'form.referral.other': 'Outro',
    'form.stay': 'Duração de estadia preferida',
    'form.stay.3-6': '3-6 meses',
    'form.stay.6-12': '6-12 meses',
    'form.stay.12+': '12+ meses',
    'form.room': 'Tipo de quarto preferido (opcional)',
    'form.room.any': 'Sem preferência',
    'form.about': 'O que te traz a Lisboa?',
    'form.about.placeholder': 'Conta-nos um pouco dos teus planos (opcional)',
    'form.submit': 'Enviar interesse',
    'form.success': 'Obrigado pelo seu interesse! Entraremos em contacto em breve.',
    'form.consent': 'Aceito ser contactado pela Living Colours sobre esta candidatura, em linha com a Política de Privacidade.',
    'form.error': 'Algo correu mal. Por favor, tenta novamente.',
    
    // FAQ
    'faq.label': 'Questões',
    'faq.title': 'Perguntas frequentes',
    'faq.q1': 'Isto é uma residência de estudantes?',
    'faq.a1': 'O Living Colours AR é um espaço de coliving, não uma residência de estudantes tradicional. Embora recebamos estudantes, também recebemos jovens profissionais, nómadas digitais e qualquer pessoa em mobilidade que valorize viver com qualidade.',
    'faq.q2': 'São permitidas estadias curtas?',
    'faq.a2': 'A nossa estadia mínima é de 3 meses. Somos desenhados para residentes que procuram estabilidade, não visitantes de curta duração.',
    'faq.q3': 'Qual é a estadia mínima?',
    'faq.a3': 'A estadia mínima é de 3 meses. A maioria dos nossos residentes fica entre 6-12 meses.',
    'faq.q4': 'Os preços são tudo incluído?',
    'faq.a4': 'Sim. A sua renda mensal inclui despesas, internet de alta velocidade, limpeza regular e acesso a todas as áreas comuns e comodidades.',
    'faq.q5': 'Posso visitar antes de reservar?',
    'faq.a5': 'Absolutamente. Assim que o edifício estiver pronto, teremos todo o gosto em organizar uma visita. Manifeste o seu interesse e mantê-lo-emos informado.',
    'faq.q6': 'Como funciona a comunidade?',
    'faq.a6': 'Organizamos eventos regulares e providenciamos espaços para conexão, mas a comunidade nunca é forçada. Você escolhe o quão social quer ser.',
    'faq.q7': 'O que é o soft launch em Julho?',
    'faq.a7': 'Antes da abertura completa em Outubro, vamos disponibilizar um número limitado de quartos a partir de Julho com um preço reduzido. Algumas comodidades ainda estarão em desenvolvimento, mas terá um desconto significativo até à abertura total. É uma ótima oportunidade para residentes pioneiros.',
    
    // Footer
    'footer.tagline': 'Coliving boutique em Lisboa',
    'footer.contact': 'Contacto',
    'footer.address': 'Avenida Almirante Reis, Lisboa',
    'footer.rights': 'Todos os direitos reservados.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
